<?xml version="1.0"?>
<robot name="arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find wheel_chair_description)/urdf/gazebo/wheel_chair_base_gazebo.xacro" />
    <xacro:include filename="$(find wheel_chair_description)/urdf/sensors/lidar_gazebo.xacro" />

    <xacro:property name="lidar_offset_x" value="0" />
    <xacro:property name="lidar_offset_y" value="0" />
    <xacro:property name="lidar_offset_z" value="${0.5*base_thickness+0.03}" />

    <wheel_chair_base/>

    <!-- lidar -->
    <joint name="lidar_joint" type="fixed">
        <origin xyz="${lidar_offset_x} ${lidar_offset_y} ${lidar_offset_z}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="laser_link"/>
    </joint>

    <xacro:rplidar prefix="laser"/>


    
   
    <!--important!!! wheel_chair is your just now xacro file name-->
    <wheel_chair_base_gazebo/>

</robot>
