<?xml version="1.0"?>
<robot name="arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find wheel_chair_description)/urdf/gazebo/wheel_chair_base_gazebo.xacro" />
    <xacro:include filename="$(find wheel_chair_description)/urdf/sensors/camera_gazebo.xacro" />

    <xacro:property name="camera_offset_x" value="${0.5*base_length-0.005}" />
    <xacro:property name="camera_offset_y" value="0" />
    <xacro:property name="camera_offset_z" value="${0.5*base_thickness+0.02}" />

    <wheel_chair_base/>

    <!-- Camera -->
    <joint name="camera_joint" type="fixed">
        <origin xyz="${camera_offset_x} ${camera_offset_y} ${camera_offset_z}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="camera_link"/>
    </joint>

    <xacro:usb_camera prefix="camera"/>


    
   
    <!--important!!! wheel_chair is your just now xacro file name-->
    <wheel_chair_base_gazebo/>

</robot>
